<?php

/*
 * Configuration for the Certificates module.
 *
 * The QUESTIONS are not in here: they live in a separate file, generated by
 * `npm run exam:sync`, and there are two versions of it.
 *
 *   exam-questions-private.php  the real exam. It is not in the repository
 *                               (which is public) and not in the web folder:
 *                               it is uploaded to the server by hand. If it is
 *                               there, it wins.
 *   exam-questions-sample.php   a public subset, so that contributors can run
 *                               the site and the tests without the real exam.
 *
 * The reason is simple: an exam whose answers can be read measures nothing, and
 * a certificate that measures nothing is worth nothing. The project's code is
 * open on purpose; the answers are not, and that is the only exception.
 */

$private = __DIR__ . '/exam-questions-private.php';
$sample  = __DIR__ . '/exam-questions-sample.php';

$bank = file_exists($private) ? require $private : (file_exists($sample) ? require $sample : []);

return [
    'name' => 'Certificates',

    // The course version, printed on the certificate
    'course_version' => '1.0',

    /*
     * How many levels the course has. It is printed on the certificate, on the
     * PDF and on the public verification page: if it does not match what the
     * site says, somebody checking another person's certificate finds two
     * different numbers and stops trusting either of them.
     *
     * The real source is the LEVELS list in public_html/js/core/levels.js; this
     * is a copy, because PHP does not read that file. Keeping them aligned is
     * `npm run validate`'s job — it compares the two numbers and stops if they
     * have gone their separate ways, which already happened when level 12 was
     * added.
     */
    'levels_count' => 34,

    // True when the server holds the real exam and not the sample one:
    // `php artisan site:check` uses it to warn before opening to the public.
    'questions_are_real' => file_exists($private),

    'questions' => $bank,
];
