/* ============================================================
   GENERATES public_html/sitemap.xml

     node tools/sitemap.mjs          rewrites the sitemap
     node tools/sitemap.mjs --check  only checks it (exits 1 if stale)

   WHY IT IS GENERATED AND NOT HAND-WRITTEN

   With one language it was thirty lines and you could keep them right by eye.
   With three languages it is over a hundred, and each one carries links to the
   other two editions (`xhtml:link rel="alternate"`), which is how you tell
   Google «these three pages are the same thing in three languages» instead of
   letting it treat them as duplicate content.

   A hundred lines with three cross-references each do not stay aligned by
   hand: the source of truth is the LEVELS list in public_html/js/core/levels.js,
   the same one the game builds its map from. When a level is born, the sitemap
   knows about it without anyone having to remember.
   ============================================================ */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(new URL(import.meta.url).pathname), '..');
const SITE = 'https://quantumarcade.it/';
const DEST = join(ROOT, 'public_html/sitemap.xml');
const CHECK = process.argv.includes('--check');

/* The three editions of the site. `dir` is the prefix in the address, `lessons`
   the lessons folder: both change, because the addresses are translated too (a
   Spanish page living under /lezioni/ is a half-translated page, and it shows). */
const LOCALES = [
  { code: 'it', dir: '',    lessons: 'lezioni',   method: 'metodo.html', privacy: 'privacy.html' },
  { code: 'en', dir: 'en/', lessons: 'lessons',   method: 'method.html', privacy: 'privacy.html' },
  { code: 'es', dir: 'es/', lessons: 'lecciones', method: 'metodo.html', privacy: 'privacidad.html' },
];

const { LEVELS, slugOf } = await import(pathToFileURL(join(ROOT, 'public_html/js/core/levels.js')).href);

/** Today's date in ISO form. */
function today() {
  return new Date().toISOString().slice(0, 10);
}

/**
 * Every page of the site, each with its address in the three languages.
 *
 * @returns {Array<{priority: string, url: Record<string, string>}>}
 */
function pages() {
  const url = (l, name) => SITE + l.dir + name;
  const perLocale = fn => Object.fromEntries(LOCALES.map(l => [l.code, fn(l)]));

  const list = [
    { priority: '1.0', url: perLocale(l => url(l, '')) },
    { priority: '0.8', url: perLocale(l => url(l, l.method)) },
  ];

  for (const lv of LEVELS) {
    list.push({
      priority: '0.8',
      url: perLocale(l => url(l, `${l.lessons}/${slugOf(lv.id, l.code)}.html`)),
    });
  }

  // privacy comes last and counts for little in search, but it must be
  // indexable: a notice search engines cannot find is a notice nobody reads
  list.push({ priority: '0.3', url: perLocale(l => url(l, l.privacy)) });

  return list;
}

/**
 * Only the languages actually published: a page promised and missing is worse
 * than a page absent.
 *
 * Since the pages became Blade views, "published" means its views folder
 * exists — no longer that an index.html does.
 */
function published() {
  return LOCALES.filter(l => existsSync(join(ROOT, 'resources/views/pages', l.code)));
}

function build(date) {
  const locales = published();
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- GENERATED by tools/sitemap.mjs (npm run sitemap) — do not edit by hand. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
  ];

  for (const p of pages()) {
    for (const l of locales) {
      lines.push('  <url>');
      lines.push(`    <loc>${p.url[l.code]}</loc>`);
      // every page lists itself and its siblings: it is the shape Google
      // expects, and Italian doubles as x-default for anyone who matches none
      for (const alt of locales) {
        lines.push(`    <xhtml:link rel="alternate" hreflang="${alt.code}" href="${p.url[alt.code]}"/>`);
      }
      lines.push(`    <xhtml:link rel="alternate" hreflang="x-default" href="${p.url.it}"/>`);
      lines.push(`    <lastmod>${date}</lastmod>`);
      lines.push('    <changefreq>monthly</changefreq>');
      lines.push(`    <priority>${p.priority}</priority>`);
      lines.push('  </url>');
    }
  }

  lines.push('</urlset>', '');

  return lines.join('\n');
}

/* The date is not content: if it were the only thing to change on each run,
   every `npm run sitemap` would dirty the diff without saying anything new.
   So the existing one is reused, unless something has genuinely changed. */
const previous = existsSync(DEST) ? readFileSync(DEST, 'utf8') : '';
const previousDate = (previous.match(/<lastmod>([\d-]+)<\/lastmod>/) || [])[1];
const unchanged = previousDate && build(previousDate) === previous;
const current = unchanged ? previous : build(today());

const locales = published().map(l => l.code).join(', ');
const count = (current.match(/<loc>/g) || []).length;

if (CHECK) {
  if (unchanged) {
    console.log(`✅ sitemap up to date: ${count} addresses (${locales})`);
  } else {
    console.error('❌ sitemap.xml is out of step with the levels: run `npm run sitemap`');
    process.exit(1);
  }
} else {
  writeFileSync(DEST, current);
  console.log(`✅ ${count} addresses in ${locales} → public_html/sitemap.xml${unchanged ? ' (already up to date)' : ''}`);
}
